name: Push image

on:
  push:
    branches: ["main"]
    paths:
      - "ecs/**"
      - ".github/workflows/deploy.yml"

permissions:
  contents: read
  id-token: write  # required for OIDC assume-role


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: prod

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
      IMAGE_TAG: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      # ---- Build + push ECS image to ECR ----
      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        working-directory: app
        env:
          ECR_REGISTRY: ${{ steps.ecr.outputs.registry }}
        run: |
          IMAGE_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

          docker build -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"